package Modelo;
// Generated 23/04/2017 06:13:43 PM by Hibernate Tools 3.2.1.GA



/**
 * InfPersonal generated by hbm2java
 */
public class InfPersonal  implements java.io.Serializable {

     private Integer idInfPersonal;
     private String categoria;
     private String asunto;
     private String TDocumento;
     private String nombres;
     private String apellidos;
     private String telefono;
     private Integer pais;
     private Integer depto;
     private Integer ciudad;
     private String correo;
     private String documento;
     private String numCelular;
     private String direccion;
     private String comentarios;
     private String adjuntaArchivo;

    public InfPersonal() {
    }

    public InfPersonal(String categoria, String asunto, String TDocumento, String nombres, String apellidos, String telefono, Integer pais, Integer depto, Integer ciudad, String correo, String documento, String numCelular, String direccion, String comentarios, String adjuntaArchivo) {
       this.categoria = categoria;
       this.asunto = asunto;
       this.TDocumento = TDocumento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.pais = pais;
       this.depto = depto;
       this.ciudad = ciudad;
       this.correo = correo;
       this.documento = documento;
       this.numCelular = numCelular;
       this.direccion = direccion;
       this.comentarios = comentarios;
       this.adjuntaArchivo = adjuntaArchivo;
    }
   
    public Integer getIdInfPersonal() {
        return this.idInfPersonal;
    }
    
    public void setIdInfPersonal(Integer idInfPersonal) {
        this.idInfPersonal = idInfPersonal;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getTDocumento() {
        return this.TDocumento;
    }
    
    public void setTDocumento(String TDocumento) {
        this.TDocumento = TDocumento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getPais() {
        return this.pais;
    }
    
    public void setPais(Integer pais) {
        this.pais = pais;
    }
    public Integer getDepto() {
        return this.depto;
    }
    
    public void setDepto(Integer depto) {
        this.depto = depto;
    }
    public Integer getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Integer ciudad) {
        this.ciudad = ciudad;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNumCelular() {
        return this.numCelular;
    }
    
    public void setNumCelular(String numCelular) {
        this.numCelular = numCelular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public String getAdjuntaArchivo() {
        return this.adjuntaArchivo;
    }
    
    public void setAdjuntaArchivo(String adjuntaArchivo) {
        this.adjuntaArchivo = adjuntaArchivo;
    }




}


